### ISSUE TITLE
Include option for daemon to delete old session files

### ISSUE THREAD

**Issue by arlake228** [perfsonar/owamp#1]
_From @arlake228 on March 14, 2015 11:59_

Original [issue 839](https://code.google.com/p/perfsonar-ps/issues/detail?id=839) created by arlake228 on 2014-02-11T16:31:21.000Z:

If powstream dies in the middle of a test, it will leave a session file lying around. Theoretically, the 
client could later come and collect that file, but in practice, he won't, and this can leave a large 
number of session files sitting around taking up the limited 'disk' space from whatever limit they 
were classified as.

This can be worked around by deleting old files and restarting owampd, but that can have adverse 
effects on any tests currently running.

The daemon should include an option for cleaning up old session files.

In the toolkit, we've put in a place a system that uses find to clear out old session files, and then restarts 
owampd. This fixes the issue; however, having this done by owampd proper, would be better.

_Copied from original issue: perfsonar/project#837_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=839#c1) originally posted by arlake228 on 2014-03-21T21:50:54.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=839#c2) originally posted by arlake228 on 2015-01-30T20:14:30.000Z:

Note: this is related to issue 1068, and should probably be worked on at the same time.

**Comment by vvidic** [comment]
I'm not sure the master owampd process know which files were created by the children in order to clean them up later.

How about we create a cron job that would remove files older than one day and not open by any current owampd process? After that we remove any old broken symlinks from the catalog directory.
This would not require a restart of the owampd process and stop active sessions.
