### ISSUE TITLE
CentOS package for TWAMP

### ISSUE THREAD

**Issue by tonin** [perfsonar/owamp#17]
@tonin commented on [Sat Jun 10 2017](https://github.com/perfsonar/twamp/issues/2)

**Comment by vvidic** [comment]
RPM packaging added in the twamp branch by https://github.com/perfsonar/owamp/commit/186421a1eb728d47f864dc67c3683cd4e34d7299. When merged into master it will produce three new packages: twamp, twamp-client and twamp-server.
