### ISSUE TITLE
bad/risky permissions on configuration files

### ISSUE THREAD

**Issue by igarny** [perfsonar/owamp#24]
Hi guys,

hopefully these need not to be executable!

t2-psdev:~>ls -l /etc/owamp-server/
total 20
-rwxr-xr-x 1 root root 3478 Oct  2 17:07 owampd.conf.default
-rwxr-xr-x 1 root root 3478 Nov  7 03:41 owamp-server.conf
-rwxr-xr-x 1 root root  265 Nov  7 03:41 owamp-server.limits
-rwxr-xr-x 1 root root 6038 Oct  2 17:07 owamp-server.limits.default

**Comment by vvidic** [comment]
On Tue, Dec 05, 2017 at 11:11:33AM +0000, Ivan Garnizov wrote:
> hopefully these need not to be executable!
> 
> t2-psdev:~>ls -l /etc/owamp-server/
> total 20
> -rwxr-xr-x 1 root root 3478 Oct  2 17:07 owampd.conf.default
> -rwxr-xr-x 1 root root 3478 Nov  7 03:41 owamp-server.conf
> -rwxr-xr-x 1 root root  265 Nov  7 03:41 owamp-server.limits
> -rwxr-xr-x 1 root root 6038 Oct  2 17:07 owamp-server.limits.default

Debian side looks fine, is this RHEL 6 or 7?

vvidic@pstest:~$ ls -l /etc/owamp-server/
total 12
-rw-r--r-- 1 root root 3478 Dec 13  2016 owamp-server.conf
-rw-r--r-- 1 root root 6038 Dec 13  2016 owamp-server.limits

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by igarny** [comment]
Hi Valentin,

Yes...I should have noted the version. It is indeed CentOS 6.

**Comment by arlake228** [comment]
Looks like the owamp .spec file is indeed setting the exec bit on those files. Appears to have been that way for 9 years. We should fix this.
