### ISSUE TITLE
owamp could be extended to also support twamp

### ISSUE THREAD

**Issue by arlake228** [perfsonar/owamp#3]
_From @arlake228 on March 14, 2015 12:49_

Original [issue 1051](https://code.google.com/p/perfsonar-ps/issues/detail?id=1051) created by arlake228 on 2015-01-22T18:15:35.000Z:

<b>Describe the enhancement:</b>
1. RFC 5357 defines a Two-Way Active Measurement Protocol based on RFC 4656 OWAMP.
2. owamp could be extended to support TWAMP controllers and servers from the most of the same source code and at the same time as supporting OWAMP.

<b>List what services, libraries, and APIs would be involved in this change:</b>
1. owamp

Commits implementing this are available starting from
https://code.google.com/r/robertshearman-owamp/source/detail?r=c6a09dd92d88516d851241db54bcf952a26e56e1&amp;name=twamp to https://code.google.com/r/robertshearman-owamp/source/detail?r=8207494cca0d9041dc2af5161be6433c6c7eb9dd&amp;name=twamp

_Copied from original issue: perfsonar/project#1049_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1051#c1) originally posted by arlake228 on 2015-01-27T15:10:26.000Z:

&lt;empty&gt;

**Comment by rshearman** [comment]
Any feedback on the changes and the timescales for them being committed into the main owamp repository?

**Comment by bltierney** [comment]
Note the code is now here:  https://github.com/rshearman/owamp/commits/twamp
Hopefully we can get this integrated for the 3.6 release.

**Comment by bltierney** [comment]
and more potentially useful code is here: https://github.com/rshearman/owamp/commits/twamp-more

**Comment by mfeit-internet2** [comment]
The patched version would be a good candidate for building as a separate tool from OWAMP that can run the round trip time test.  That would keep it separate from classic OWAMP in case there's a problem with the patch.

When I have some time, I'll download and build it and see how it works.

**Comment by tonin** [comment]
PR https://github.com/perfsonar/owamp/pull/16 contains the changes mentioned in this issue.  It needs proper integration testing before release.

**Comment by arlake228** [comment]
Should we make this an epic issue and split-up? We really shouldn't have a task as big as 21 points. Or maybe the 21 points is no longer applicable since we think the pull request looks pretty good?

**Comment by tonin** [comment]
Yes, I added the 21 points to cover for work already done.  All that remains is testing, so if you prefer to count only what remains we can make it 2 or 3.

There is already an EPIC at https://github.com/perfsonar/project/issues/1123

**Comment by arlake228** [comment]
I'd say mark it as 2 or 3. We really want the estimate to be mostly capturing what work is left to be done. If we were to close it out as is now this sprint would look like we got twice as much done as any other sprint which isn't really accurate since the work has been going on awhile. We probably should have been tracking it sooner so we could have captured the work being done as it happens, but all this started before we were completely ramped-up on zenhub and all that so its little bit of a special case.

**Comment by tonin** [comment]
Yes, I added the 21 points to cover for work already done.  All that remains is testing, so if you prefer to count only what remains we can make it 2 or 3.

There is already an EPIC at https://github.com/perfsonar/project/issues/1123

**Comment by erik-geant** [comment]
this work has been integrated and merged into owamp master, which now builds both toolsets

there's still some work that can be done (e.g. ptwstream), but let's make new issues for such details ...

**Comment by tonin** [comment]
Yes, follow up is on https://github.com/perfsonar/project/issues/1123
