### ISSUE TITLE
I2Addr functions block contacting DNS server even when node name not requested

### ISSUE THREAD

**Issue by arlake228** [perfsonar/owamp#4]
_From @arlake228 on March 14, 2015 12:50_

Original [issue 1055](https://code.google.com/p/perfsonar-ps/issues/detail?id=1055) created by arlake228 on 2015-01-26T10:15:28.000Z:

<b>What steps will reproduce the problem?</b>
1. I2Addr functions block contacting DNS server even when node name not requested
2. owamp uses I2Addr functions for test sessions, but never requests the name of the peer node. Therefore, this results in unnecessary delays if there is any delay in contacting the DNS server.

<b>What is the expected output? What do you see instead?</b>
No delay in using I2Addr APIs when not requesting peer node name.

<b>What version of the product are you using? On what operating system?</b>
1.2-2 on Debian Linux

<b>Please provide any additional information below.</b>

Commits for tests and fixes available here:
https://code.google.com/r/rshearma-i2util/source/detail?r=3068e9290d34a09491d54dbb87033cc3c3931c61&amp;name=addr-rdns
https://code.google.com/r/rshearma-i2util/source/detail?r=c43d3b2243e1da16fb6a38cb3d7f63aa16626c63&amp;name=addr-rdns

_Copied from original issue: perfsonar/project#1053_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1055#c1) originally posted by arlake228 on 2015-01-27T15:13:10.000Z:

&lt;empty&gt;

**Comment by rshearman** [comment]
FYI, I've rebased the changes to latest master and moved to hosting on github. New URL here:
https://github.com/perfsonar/i2util/compare/master...rshearman:addr-rdns

**Comment by vvidic** [comment]
I2util and owamp changes merged for 4.2.0 release, closing.
