### ISSUE TITLE
segfault when breaking during password entry

### ISSUE THREAD

**Issue by dopheide-esnet** [perfsonar/owamp#41]
While testing authentication with owping, I found that if I hit ctrl+c when prompted for the password the application would segfault:

[dopheide@sec-vm ~]$ owping -AA -u dopheide hous-owamp.es.net
Enter passphrase for identity 'dopheide': Segmentation fault

Likely minor, but could point to an exception handling issue.

**Comment by vvidic** [comment]
Change merged for release in 4.2.0.
