### ISSUE TITLE
owampd authentication documentation

### ISSUE THREAD

**Issue by dopheide-esnet** [perfsonar/owamp#42]
This is just a usability issue.  Being new to owamp and perfsonar usage, I struggled to figure out how to get an authenticated/encrypted session connected.  (I imagine most use cases don't use it, but I hope to build a protocol analyzer and needed pcaps with those options enabled.)

1)  It would be helpful if the README/INSTALL files pointed to the process to use pfstore to create the needed .pfs file.
2)  This may be a result of how the rpm packages are built for CentOS 7, but the owampd man page refers to owawpd.pfs, however the daemon actually tries to read owamp-server.pfs.  

I'm happy to provide a pull request for (1) if you'd like, but I'm not sure how you may want to handle (2).

**Comment by vvidic** [comment]
I think it would be best to update the man pages with this info, if you still care to make a pull request?

**Comment by dopheide-esnet** [comment]
Just submitting Pull #51.

**Comment by vvidic** [comment]
I will try to rename man pages to match the names of config files we have now.

**Comment by vvidic** [comment]
Documentation updated in the 4.2.0 branch.
