### ISSUE TITLE
owamp should take configure options into account when compiling debug-specific code

### ISSUE THREAD

**Issue by arlake228** [perfsonar/owamp#5]
_From @arlake228 on March 14, 2015 12:52_

Original [issue 1067](https://code.google.com/p/perfsonar-ps/issues/detail?id=1067) created by arlake228 on 2015-01-30T10:23:34.000Z:

<b>What steps will reproduce the problem?</b>
1. Configure owamp without --enable-debug option and run &quot;make&quot;
2. Observe that logs are emitted with filenames and line numbers, and debugging CLI options are present in programs.

<b>What is the expected output? What do you see instead?</b>
Unless &quot;--enable-debug&quot; is specified to configure expect that debugging CLI options are not included and log messages don't include filenames and line numbers.

<b>What version of the product are you using? On what operating system?</b>
3.4-10

<b>Please provide any additional information below.</b>

Fix available here:
https://code.google.com/r/robertshearman-owamp/source/detail?r=0e429527aefbc65fe9570c2896245264bbc3336e&amp;name=debugflag

Unrelated compile fix for an earlier commit of mine is also available here:
https://code.google.com/r/robertshearman-owamp/source/detail?r=6a7cd19f4766a3ac4b8625b403c9f290188dff78&amp;name=debugflag

_Copied from original issue: perfsonar/project#1065_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1067#c1) originally posted by arlake228 on 2015-01-30T18:12:25.000Z:

&lt;empty&gt;

**Comment by rshearman** [comment]
Any feedback on the change and the timescales for it being committed into the main owamp repository?

**Comment by vvidic** [comment]
Do we still have these patches somewhere?

**Comment by deastoe** [comment]
#62 contains these and some related patches.
