### ISSUE TITLE
owamp doesn't work with link-local addresses

### ISSUE THREAD

**Issue by arlake228** [perfsonar/owamp#6]
_From @arlake228 on March 14, 2015 12:52_

Original [issue 1070](https://code.google.com/p/perfsonar-ps/issues/detail?id=1070) created by arlake228 on 2015-01-31T10:56:52.000Z:

<b>What steps will reproduce the problem?</b>
1. owping &lt;IPv6LLAddrOfOwampd&gt; 
2. When a client requests an IPv6 link-local address to be used for a test session endpoint, the bind to the address fails since a scope isn't provided and a link-local address isn't valid without a scope indicating which link (interface) it applies to.

<b>What is the expected output? What do you see instead?</b>
Expect the owping to connect, successfully run and provide a summary of results.

<b>What version of the product are you using? On what operating system?</b>
3.4-10

<b>Please provide any additional information below.</b>

Fix proposed here:
https://code.google.com/r/robertshearman-owamp/source/detail?r=19a405f6fc385fe5132be3bf0043a9cd5efec6e6&amp;name=v6-link-local

_Copied from original issue: perfsonar/project#1068_

**Comment by vvidic** [comment]
It seems this was fixed some time ago.
