### ISSUE TITLE
Sending a request to client-sender to implement a test session with client-reflector

### ISSUE THREAD

**Issue by tritamk14** [perfsonar/owamp#69]
Hi all, I need to use twping to send a request to a juniper device to implement a test session with another juniper device. Can this tool support that feature?

**Comment by mfeit-internet2** [comment]
Twping doesn't support asking another device to do a twping on your behalf.

Juniper would be unlikely to support that without authentication for a long list of reasons, so your best bet would be to get access to the device and ask it to do the test.  Their implementation may also not be this one, so any change we could make wouldn't necessarily affect their products.
