### ISSUE TITLE
Compile on Raspberry PI 3/4

### ISSUE THREAD

**Issue by resper-guo** [perfsonar/owamp#70]
I want to compile owamp on RPI, can someone tell me how to build it, thanks.

**Comment by mfeit-internet2** [comment]
Directions for compilation are in the `INSTALL` file in the top-level directory of the sources.

There are also pre-built binaries for various flavors of Debian and Ubuntu that will run on a Pi in the [perfSONAR repository](https://docs.perfsonar.net/install_debian.html#step-1-configure-apt).

**Comment by resper-guo** [comment]
@mfeit-internet2 , thank you very much for your reply.
I can't found the configure in top-level directory of the sources.
I tried to use autoconf to generate configure, but failed.
