### ISSUE TITLE
owping

### ISSUE THREAD

**Issue by MayPyoneHann** [perfsonar/owamp#72]
I am testing one-way ping to measure the delay of the network. In my case, I have a problem. The error shows as follows:

owping: NTP: Status UNSYNC (clock offset issues likely)
owping: NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
owping: Unable to open control connection to 2001::100.

Please advise me to tackle my error message, Sir.
Thank you.

**Comment by mfeit-internet2** [comment]
Owping considers not having ntpd running a fatal error.
