### ISSUE TITLE
powstream seems to resets sequence numbers for each subsession

### ISSUE THREAD

**Issue by ottojwittner** [perfsonar/owamp#78]
When receiving raw-output from a latencybg test (via pscheduler-archiver-rabbitmq) output for each sub-session seems to restart its sequence numbers at 0. Given that the latencybg test is suppose to offer a continuous test, this is unfortunate, and e.g. packet-out-of-order analysis across sub-session boundaries becomes awkward and imprecise.
Continuous sequence numbering (up until owamp's 32 bit max value) is requested.

**Comment by arlake228** [comment]
Assigning to Sarah so we can discuss
